name: Docker Release Staging

on:
  push:
    tags:
      - 'test*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build dockerfile
        uses: nick-invision/retry@v2
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          VERSION: ${{ steps.checkver.outputs.version }}
        with:
          timeout_minutes: 120
          max_attempts: 3
          command: |
            docker buildx build \
            --platform=linux/amd64 \
            --output "type=image,push=true" \
            --file ./Dockerfile . \
            --tag $(echo "${DOCKER_USERNAME}" | tr '[:upper:]' '[:lower:]')/nodestatus:test
